### ISSUE TITLE
it not works in gazebo,why?

### ISSUE THREAD

**Issue by Ruid6** [RealManRobot/rm_robot#3]
[ INFO] [1703060753.798087647, 0.173000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
[ERROR] [1703060753.905019560, 0.173000000]: No p gain specified for pid.  Namespace: /arm/gazebo_ros_control/pid_gains/joint1
[ERROR] [1703060753.905518015, 0.173000000]: No p gain specified for pid.  Namespace: /arm/gazebo_ros_control/pid_gains/joint2
[ERROR] [1703060753.905706434, 0.173000000]: No p gain specified for pid.  Namespace: /arm/gazebo_ros_control/pid_gains/joint3
[ERROR] [1703060753.905858700, 0.173000000]: No p gain specified for pid.  Namespace: /arm/gazebo_ros_control/pid_gains/joint4
[ERROR] [1703060753.906066545, 0.173000000]: No p gain specified for pid.  Namespace: /arm/gazebo_ros_control/pid_gains/joint5
[ERROR] [1703060753.906212606, 0.173000000]: No p gain specified for pid.  Namespace: /arm/gazebo_ros_control/pid_gains/joint6

It will fall to the ground.like this.
![image](https://github.com/RealManRobot/rm_robot/assets/48819558/b29967d9-1207-4aca-8c24-50b83e9b685c)

**Comment by kaola-zero** [comment]
We have been update , you can pull the new code try again

**Comment by Ruid6** [comment]
> We have been update , you can pull the new code try again

thanks,it works!
